#include "dusklight_online/game/randomizer_item_names.hpp"

#include <array>

namespace dusklight_online::game {

std::string_view randomizer_item_name(uint8_t itemId) {
    static constexpr auto names = [] {
        std::array<std::string_view, 256> names{};
        names[0x01] = "Green Rupee";
        names[0x02] = "Blue Rupee";
        names[0x03] = "Yellow Rupee";
        names[0x04] = "Red Rupee";
        names[0x05] = "Purple Rupee";
        names[0x06] = "Orange Rupee";
        names[0x07] = "Silver Rupee";
        names[0x0A] = "Bombs 5";
        names[0x0B] = "Bombs 10";
        names[0x0C] = "Bombs 20";
        names[0x0D] = "Bombs 30";
        names[0x0E] = "Arrows 10";
        names[0x0F] = "Arrows 20";
        names[0x10] = "Arrows 30";
        names[0x12] = "Seeds 50";
        names[0x13] = "Foolish Item";
        names[0x14] = "Ordon Spring Portal";
        names[0x15] = "South Faron Portal";
        names[0x16] = "Water Bombs 5";
        names[0x17] = "Water Bombs 10";
        names[0x18] = "Water Bombs 15";
        names[0x1A] = "Bomblings 5";
        names[0x1B] = "Bomblings 10";
        names[0x21] = "Piece of Heart";
        names[0x22] = "Heart Container";
        names[0x2A] = "Ordon Shield";
        names[0x2B] = "Wooden Shield";
        names[0x2C] = "Hylian Shield";
        names[0x30] = "Magic Armor";
        names[0x31] = "Zora Armor";
        names[0x32] = "Shadow Crystal";
        names[0x35] = "Progressive Wallet";
        names[0x39] = "Upper Zoras River Portal";
        names[0x3A] = "Castle Town Portal";
        names[0x3B] = "Gerudo Desert Portal";
        names[0x3C] = "North Faron Portal";
        names[0x3E] = "Hawkeye";
        names[0x3F] = "Progressive Sword";
        names[0x40] = "Gale Boomerang";
        names[0x41] = "Spinner";
        names[0x42] = "Ball and Chain";
        names[0x43] = "Progressive Bow";
        names[0x44] = "Progressive Clawshot";
        names[0x45] = "Iron Boots";
        names[0x46] = "Progressive Dominion Rod";
        names[0x48] = "Lantern";
        names[0x4A] = "Progressive Fishing Rod";
        names[0x4B] = "Slingshot";
        names[0x4D] = "Kakariko Gorge Portal";
        names[0x4E] = "Kakariko Village Portal";
        names[0x4F] = "Giant Bomb Bag";
        names[0x50] = "Bomb Bag";
        names[0x52] = "Death Mountain Portal";
        names[0x57] = "Zoras Domain Portal";
        names[0x60] = "Empty Bottle";
        names[0x61] = "Red Potion Shop";
        names[0x63] = "Blue Potion Shop";
        names[0x65] = "Bottle with Half Milk";
        names[0x66] = "Lantern Oil Shop";
        names[0x73] = "Fairy Tears";
        names[0x75] = "Bottle with Great Fairies Tears";
        names[0x80] = "Renados Letter";
        names[0x81] = "Invoice";
        names[0x82] = "Wooden Statue";
        names[0x83] = "Ilias Charm";
        names[0x84] = "Horse Call";
        names[0x85] = "Forest Temple Small Key";
        names[0x86] = "Goron Mines Small Key";
        names[0x87] = "Lakebed Temple Small Key";
        names[0x88] = "Arbiters Grounds Small Key";
        names[0x89] = "Snowpeak Ruins Small Key";
        names[0x8A] = "Temple of Time Small Key";
        names[0x8B] = "City in the Sky Small Key";
        names[0x8C] = "Palace of Twilight Small Key";
        names[0x8D] = "Hyrule Castle Small Key";
        names[0x8E] = "Gerudo Desert Bulblin Camp Key";
        names[0x8F] = "Lake Hylia Portal";
        names[0x90] = "Aurus Memo";
        names[0x91] = "Asheis Sketch";
        names[0x92] = "Forest Temple Big Key";
        names[0x93] = "Lakebed Temple Big Key";
        names[0x94] = "Arbiters Grounds Big Key";
        names[0x95] = "Temple of Time Big Key";
        names[0x96] = "City in the Sky Big Key";
        names[0x97] = "Palace of Twilight Big Key";
        names[0x98] = "Hyrule Castle Big Key";
        names[0x99] = "Forest Temple Compass";
        names[0x9A] = "Goron Mines Compass";
        names[0x9B] = "Lakebed Temple Compass";
        names[0x9D] = "Bottle with Lantern Oil";
        names[0xA5] = "Progressive Mirror Shard";
        names[0xA8] = "Arbiters Grounds Compass";
        names[0xA9] = "Snowpeak Ruins Compass";
        names[0xAA] = "Temple of Time Compass";
        names[0xAB] = "City in the Sky Compass";
        names[0xAC] = "Palace of Twilight Compass";
        names[0xAD] = "Hyrule Castle Compass";
        names[0xAE] = "Mirror Chamber Portal";
        names[0xAF] = "Snowpeak Portal";
        names[0xB6] = "Forest Temple Dungeon Map";
        names[0xB7] = "Goron Mines Dungeon Map";
        names[0xB8] = "Lakebed Temple Dungeon Map";
        names[0xB9] = "Arbiters Grounds Dungeon Map";
        names[0xBA] = "Snowpeak Ruins Dungeon Map";
        names[0xBB] = "Temple of Time Dungeon Map";
        names[0xBC] = "City in the Sky Dungeon Map";
        names[0xBD] = "Palace of Twilight Dungeon Map";
        names[0xBE] = "Hyrule Castle Dungeon Map";
        names[0xBF] = "Sacred Grove Portal";
        names[0xC0] = "Male Beetle";
        names[0xC1] = "Female Beetle";
        names[0xC2] = "Male Butterfly";
        names[0xC3] = "Female Butterfly";
        names[0xC4] = "Male Stag Beetle";
        names[0xC5] = "Female Stag Beetle";
        names[0xC6] = "Male Grasshopper";
        names[0xC7] = "Female Grasshopper";
        names[0xC8] = "Male Phasmid";
        names[0xC9] = "Female Phasmid";
        names[0xCA] = "Male Pill Bug";
        names[0xCB] = "Female Pill Bug";
        names[0xCC] = "Male Mantis";
        names[0xCD] = "Female Mantis";
        names[0xCE] = "Male Ladybug";
        names[0xCF] = "Female Ladybug";
        names[0xD0] = "Male Snail";
        names[0xD1] = "Female Snail";
        names[0xD2] = "Male Dragonfly";
        names[0xD3] = "Female Dragonfly";
        names[0xD4] = "Male Ant";
        names[0xD5] = "Female Ant";
        names[0xD6] = "Male Dayfly";
        names[0xD7] = "Female Dayfly";
        names[0xD8] = "Progressive Fused Shadow";
        names[0xE0] = "Poe Soul";
        names[0xE1] = "Progressive Hidden Skill";
        names[0xE8] = "Bridge of Eldin Portal";
        names[0xE9] = "Progressive Sky Book";
        names[0xED] = "Purple Rupee Links House";
        names[0xEE] = "North Faron Woods Gate Key";
        names[0xF3] = "Gate Keys";
        names[0xF4] = "Ordon Pumpkin";
        names[0xF5] = "Ordon Cheese";
        names[0xF6] = "Snowpeak Ruins Bedroom Key";
        names[0xF9] = "Goron Mines Key Shard";
        names[0xFE] = "Coro Key";

        // items.yaml lists progressive rewards under one logical pool ID, but
        // ItemService reports the concrete tier selected by
        // verifyProgressiveItem(). Give every possible resolved tier the same
        // player-facing pool name so later upgrades never become unknown.
        names[0x28] = "Progressive Sword";
        names[0x29] = "Progressive Sword";
        names[0x49] = "Progressive Sword";
        names[0x36] = "Progressive Wallet";
        names[0x3D] = "Progressive Fishing Rod";
        names[0x47] = "Progressive Clawshot";
        names[0x4C] = "Progressive Dominion Rod";
        names[0x55] = "Progressive Bow";
        names[0x56] = "Progressive Bow";
        names[0xA6] = "Progressive Mirror Shard";
        names[0xA7] = "Progressive Mirror Shard";
        names[0xD9] = "Progressive Fused Shadow";
        names[0xDA] = "Progressive Fused Shadow";
        names[0xDB] = "Progressive Mirror Shard";
        names[0xE2] = "Progressive Hidden Skill";
        names[0xE3] = "Progressive Hidden Skill";
        names[0xE4] = "Progressive Hidden Skill";
        names[0xE5] = "Progressive Hidden Skill";
        names[0xE6] = "Progressive Hidden Skill";
        names[0xE7] = "Progressive Hidden Skill";
        names[0xEA] = "Progressive Sky Book";
        names[0xEB] = "Progressive Sky Book";
        names[0xFA] = "Goron Mines Key Shard";
        names[0xFD] = "Goron Mines Key Shard";
        return names;
    }();

    const std::string_view name = names[itemId];
    return name.empty() ? std::string_view{"Unknown Item"} : name;
}

} // namespace dusklight_online::game
